// Code generated by struct2interface; DO NOT EDIT.

package grpc

import (
	"context"

	helloworldv1 "github.com/douyu/proto/gen/go/api/helloworld/v1"
	hwv1 "github.com/douyu/proto/gen/go/api/hw/v1"
)

// ExampleInterface ...
type ExampleInterface interface {
	SayHello(ctx context.Context, req *helloworldv1.SayHelloRequest) (*helloworldv1.SayHelloResponse, error)
	HwSayHello(ctx context.Context, req *hwv1.SayHelloRequest) (*hwv1.SayHelloResponse, error)
}
